# -*- coding: utf-8 -*-
"""B_V_V_SURYA_DURGA_PRASAS_(256Q6A4516)_CSE_AIDS (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EK79YHfJTN2gPQxHvWGVJx-UUlylOzzL
"""

print("-----------------------------------")
print("  STUDENT PROGRESS TRACKER SYSTEM  ")
print("-----------------------------------")

name = input("Enter The Student Name: ")
branch = input("Enter The Student Branch: ")
roll = input("Enter The Student Roll Number: ")
year = input("Enter The Student Year: ")
sem = input("Enter The Student Semester: ")
#number of subjects
n = int(input("Enter The Number Of Subjects: "))
marks = []
total = 0.0

for i in range(1, n + 1):
    m = float(input(f"Enter marks for Subject {i}: "))
    marks.append(m)
    total += m

average = total / n

#GradeCalculation
if average >= 90:
    grade = "A"
elif average >= 75:
    grade = "B"
elif average >= 50:
    grade = "C"
elif average >= 35:
    grade = "D"
else:
    grade = "Fail"

#Pass/Fail Logic
results = "Pass"
for m in marks:
    if m < 35:
        results = "Fail"
        break

#DisplayReport
print("-----------------------------------")
print("     STUDENT PROGRESS REPORT       ")
print("-----------------------------------")
print(f"Name        : {name}")
print(f"Branch      : {branch}")
print(f"Roll No     : {roll}")
print(f"Year        : {year}")
print(f"Semester    : {sem}")
print(f"Total Marks : {total}")
print(f"Average     : {average}")
print(f"Grade       : {grade}")
print(f"Results     : {results}")
print("------------------------------------")

#MENUSYSTEM
while True:
    print("\nWhat do you want to do next?")
    print("1. Enter marks again")
    print("2. View report again")
    print("3. Save report to a text file and exit")
    print("4. Exit")
    choice = input("Enter your choice: ")

    #ENTER AGAIN
    if choice == "1":

        name = input("Enter The Student Name: ")
        branch = input("Enter The Student Branch: ")
        roll = input("Enter The Student Roll Number: ")
        year = input("Enter The Student Year: ")
        sem = input("Enter The Student Semester: ")

        n = int(input("Enter The Number Of Subjects: "))

        marks = []
        total = 0.0

        for i in range(1, n + 1):
            m = float(input(f"Enter marks for Subject {i}: "))
            marks.append(m)
            total += m

        average = total / n

        if average >= 90:
            grade = "A"
        elif average >= 75:
            grade = "B"
        elif average >= 50:
            grade = "C"
        elif average >= 35:
            grade = "D"
        else:
            grade = "Fail"

        results = "Pass"
        for m in marks:
            if m < 35:
                results = "Fail"
                break

        print("-----------------------------------")
        print("     STUDENT PROGRESS REPORT       ")
        print("-----------------------------------")
        print(f"Name        : {name}")
        print(f"Branch      : {branch}")
        print(f"Roll No     : {roll}")
        print(f"Year        : {year}")
        print(f"Semester    : {sem}")
        print(f"Total Marks : {total}")
        print(f"Average     : {average}")
        print(f"Grade       : {grade}")
        print(f"Results     : {results}")
        print("-----------------------------------")

    #LASTREPORT
    elif choice == "2":
        if has_report:
            print("-----------------------------------")
            print("     STUDENT PROGRESS REPORT       ")
            print("-----------------------------------")
            print(f"Name        : {last_name}")
            print(f"Branch      : {last_branch}")
            print(f"Roll No     : {last_roll}")
            print(f"Year        : {last_year}")
            print(f"Semester    : {last_sem}")
            print(f"Total Marks : {last_total}")
            print(f"Average     : {last_average}")
            print(f"Grade       : {last_grade}")
            print(f"Results     : {last_results}")
            print("-----------------------------------")
        else:
            print("No report available. Please enter marks first.")

    #SAVETOFILE
    elif choice == "3":
        filename = f"{name.replace(' ','_')}.txt"
        with open(filename, "w") as file:
            file.write("-----------------------------------\n")
            file.write("     STUDENT PROGRESS REPORT       \n")
            file.write("-----------------------------------\n")
            file.write(f"Name        : {name}\n")
            file.write(f"Branch      : {branch}\n")
            file.write(f"Roll No     : {roll}\n")
            file.write(f"Year        : {year}\n")
            file.write(f"Semester    : {sem}\n")
            file.write(f"Total Marks : {total}\n")
            file.write(f"Average     : {average}\n")
            file.write(f"Grade       : {grade}\n")
            file.write(f"Results     : {results}\n")
            file.write("-----------------------------------\n")

        print(f"Report saved to {filename}")
        break

    #EXIT
    elif choice == "4":
        print("Exiting... Thank you!")
        break
    else:
        print("Invalid choice! Please enter 1, 2, 3 or 4.")